from button import Button

SCREEN_WIDTH, SCREEN_HEIGHT = 800, 850
BUTTON_WIDTH, BUTTON_HEIGHT = SCREEN_WIDTH // 4, 50
GRID_COLUMNS, GRID_ROWS = 50, 50
GAP = SCREEN_WIDTH // GRID_COLUMNS
COLOURS = {
    'WHITE': (255, 255, 255),
    'RED': (255, 0, 0),
    'GREEN': (0, 255, 0),
    'BLACK': (0, 0, 0),
    'ORANGE': (255, 165, 0),
    'PURPLE': (128, 0, 128),
    'TURQUOISE': (64, 224, 208)
}
BUTTONS = [
    Button(COLOURS['ORANGE'], 0, SCREEN_HEIGHT - BUTTON_HEIGHT, BUTTON_WIDTH, BUTTON_HEIGHT, 'A*'),
    Button(COLOURS['PURPLE'], BUTTON_WIDTH, SCREEN_HEIGHT - BUTTON_HEIGHT, BUTTON_WIDTH, BUTTON_HEIGHT, 'Dijkstra'),
    Button(COLOURS['TURQUOISE'], BUTTON_WIDTH * 2, SCREEN_HEIGHT - BUTTON_HEIGHT, BUTTON_WIDTH, BUTTON_HEIGHT, 'Greedy'),
    Button(COLOURS['RED'], BUTTON_WIDTH * 3, SCREEN_HEIGHT - BUTTON_HEIGHT, BUTTON_WIDTH, BUTTON_HEIGHT, 'Reset')
]